# compile TM FAST Library files
vcom ../SRC/TM_FAST_Library/tfl_fast_user_lib_p.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/SignedMult_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/true_dual_port_ram_dual_clock_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/NegEdge_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/NegSignalEdge_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/PosEdge_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/PosSignalEdge_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/RS_FF_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/BitLogic/SR_FF_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Comparator/Compare_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Comparator/Compare_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/I_DI_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/I_DI_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/INV_DI_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/INV_DI_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/INV_I_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Converter/INV_I_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/ADSU_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/ClkTick100k_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/lpm_div16/lpm_div16.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/lpm_div32/lpm_div32.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB100_FMMul32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB101_FMMul16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB102_FMDiv32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB103_FMDiv16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB104_FMAbs32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB105_FMAbs16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB106_FMAdd32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB107_FMAdd16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB108_FMSub32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB109_FMSub16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB110_DatSel32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB111_DatSel16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB112_BiScale_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB113_TP32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB114_TOn32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB115_TOf32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB116_TP16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB117_TOn16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB118_TOf16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB119_CP_Gen_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB120_CTUD32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB121_CTU16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB122_CTD16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB123_CTUD16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB124_Shift_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB125_Shift2_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB126_Shift4_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB127_Shift8_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB76_WordPack_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB76_WordPack_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB77_WordCast_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB77_WordCast_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB78_BitSum_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB79_Encode_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB79_Encode_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB80_Period32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB81_Period16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB82_Freq32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB83_Freq16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB84_Shift32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB85_Shift16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB86_BitPick_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB86_BitPick_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB87_BitPick_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB87_BitPick_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB88_BitShift_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB89_BitShift_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB90_BitCast_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB90_BitCast_DW_U_ea.vhd  -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB91_BitCast_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB91_BitCast_W_U_ea.vhd   -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB92_BitPack_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB92_BitPack_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB93_BitPack_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB93_BitPack_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB94_BitInsert32_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB95_BitInsert16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB95_BitInsert16_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB96_FIFO32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB97_FIFO16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB98_LIFO32_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/FBLibrary/FB99_LIFO16_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Inc_Encoder/Encoder_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Inc_Encoder/Inc_Enc_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Inc_Encoder/QuadDec_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_B_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_B_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_ClockOut_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_Input_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSIListenIn_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSIListenIn_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_B_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_B_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/Move/Move_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_W_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/ShiftRotate/ShiftRotate_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_ClockOut_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSI_Input_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSIListenIn_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/SSI_Encoder/SSIListenIn_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_DW_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_W_U_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_DW_ea.vhd -2008
vcom ../SRC/TM_FAST_Library/WordLogic/WordLogic_W_ea.vhd -2008